/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "BlogPosts": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "CoworkingSpaces": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Reports": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "myApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "viteSite": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}