version = 0.1
[production.deploy.parameters]
stack_name = "coworking-offices-api"
resolve_s3 = true
s3_prefix = "coworking-offices-api"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
