AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template to deploy the coworking backend as a Lambda behind API Gateway.

Globals:
  Function:
    Runtime: nodejs22.x
    MemorySize: 512
    Timeout: 30
    Environment:
      Variables:
        NODE_ENV: production

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      CodeUri: .
      Description: Backend API for coworking spaces
      Events:
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          NODE_ENV: production
          COWORKING_SPACES_TABLE: !Ref CoworkingSpacesTable
          SERVICES_TABLE: !Ref ServicesTable
          SPACE_SERVICES_TABLE: !Ref SpaceServicesTable
          PRICING_PACKAGES_TABLE: !Ref PricingPackagesTable
          REPORTS_TABLE: !Ref ReportsTable

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"