name: CI/CD Deployment
permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - main
jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Install dependencies
        run: npm ci
      - name: Install AWS SAM CLI
        run: pip3 install aws-sam-cli
      - name: Deploy SAM application
        working-directory: server
        run: sam build --config-env production && sam deploy --config-env production --no-confirm-changeset --no-fail-on-empty-changeset
  deploy_frontend:
    runs-on: ubuntu-latest
    env:
      VITE_API_KEY: ${{ secrets.API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Install dependencies
        run: npm ci
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build
        run: npm run build:frontend
      - name: Deploy static website to S3
        run: aws s3 sync dist/public s3://${{ secrets.FRONTEND_S3_BUCKET }} --delete
      - name: Invalidate Cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CDN_ID }} --paths "/*"